# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9582ea45c1054543edf6337760005ae6cb50eb19ebde56459e33805e56a7857716f8b45843997c5d88c35844886afa0548c84db03b7b602aba1717b7e986b7c

test:
  secret_key_base: a093b0b7cf873438e60fdf66d2eca8a2b5e985c71d828c598d979a1a9966b33f5022fc2e6fca7db0479684c9aa965dad2e671794c3d720c25ab6b4baf78ad92e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
